package templates

import (
	"strings"
	"text/template"
)

var (
	title = template.FuncMap{
		"Title": strings.Title,
	}
	Generator = template.Must(template.New("generator").Funcs(title).Parse(`// code generated by go-mobile-collection. DO NOT EDIT.
// WARNING - These collections are not thread-safe

package {{.Package}}

import (
	"encoding/json"
	"github.com/pkg/errors"
)
{{ range .Types }}
{{ if .TypeNamed }}{{ template "typeNamed" . }}{{ else }}{{ template "embed" . }}{{ end }}
{{ end }}`))
)
