package templates

import (
	"strings"
	"text/template"
)

var (
	title = template.FuncMap{
		"Title": strings.Title,
	}
	Generator = template.Must(template.New("generator").Funcs(title).Parse(`{{ if .Header }}{{ template "header" . }}{{ end }}
{{ range .Types }}
{{ if .TypeNamed }}{{ template "typeNamed" . }}{{ else }}{{ template "embed" . }}{{ end }}
{{ end }}
`))
	GeneratorBase = template.Must(Generator.New("header").Funcs(title).Parse(`{{ define "header" }}// Code generated by go-mobile-collection. DO NOT EDIT.
// WARNING - These collections are not thread-safe

package {{.Package}}

import (
	"encoding/json"

	"github.com/pkg/errors"
)
{{ end }}`))
)
